name = "preact-ssr-worker"
type = "webpack"

account_id = "33c9d6250b2ef4a5d81b9ba11249eda3"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && rm -rf public/src && cp -r src public && npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = "./public" # Add the directory with your static assets!
entry-point = "." # JS folder serving your assets

# [secrets]
# STELLAR_STAGING_TOKEN
